spring:
  messages:
    encoding: UTF-8

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/recipe?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: root
    password: 960928
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  sql:
    init:
      mode: never
  jpa:
    # Choose either MySQL 8 or MySQL 5 below
    # For MySQL 8
    database-platform: org.hibernate.dialect.MySQL8Dialect
    #For MySQL 5
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
#Cloudinary Properties
cloudinary:
  api-key: 993835859763347
  api-secret: 5n9D9b6XK_SdxIobbfHv_YP1rp0
  cloud-name: dkcphgfnh

mail:
  host: smtp.gmail.com
  port: 587
  username: anna.mileva92@gmail.com
  password: "btngewuzegmbptou"

site:
    base:
      url: http://localhost:8080
